# Check out https://docs.codemagic.io/getting-started/building-a-react-native-app/ for more information
# Please review and update values in curly braces

workflows:
    react-native:
        name: Production Release
        instance_type: mac_mini
        max_build_duration: 120
        environment:
            vars:
                XCODE_WORKSPACE: "Constructo2"
                XCODE_SCHEME: "Constructo2"
                REACT_APP_API_KEY: Encrypted(Z0FBQUFBQmZ3NWlsU1RoNTVDOF9OS2xZc01Tdnc3ZldCTlFNU3JCQ2ZBdVpldkdZN2lEcmVoTlBQZVVrb1N1UE01bHR4WVJqVVRyR29DOGFFWW9BR19UcmRwOGZkVjNlVTJibnBmMzBXdXdCV2txN2JveEZ1c3I5bjFMWUpMemFxS0ZJSnBTWHhVOGM=)
                REACT_APP_AUTH_DOMAIN: Encrypted(Z0FBQUFBQmZ3NWl2MXVnLU8tOEVOM29YbzhqNUJfUjA3eDBmTnFUMkRKQWRSa2daWXkyOXQzSDVSTzhvcWY3MFNjZkQxTDJMT2dYRnhaaWVWV1p3Z2h2WkItSFBybzlKVUNMc0w1eERvcnFyVUpsSGcyVVUzTEpGakFWbC10cmljUmdEbXllVjNKN2o=)
                REACT_APP_DATABASE_URL: Encrypted(Z0FBQUFBQmZ3NWkzVDJ0OWl6bzAwdW5CcXU5ZmtRVXdoYXJ2LVY5bjZBYXE5V1B3Y0dlQjJGS1pZSVBVak1tamZ1V1JSRkFGai1xVEs3cjZ1QS1uV3NYMmpvWVdWek93cU9VNnI5andQeE5IUVFua0xYc1NwNG01STdSNmp5d19nX1JLdUtGRDAtVzY=)
                REACT_APP_PROJECT_ID: Encrypted(Z0FBQUFBQmZ3NWpBTlVXN2E4LVFCT0FLa2F0NDhTSG05eHF3TUJNcGhZQlI5ZFlZSW5qaVBySXgwNUlsUDBCbEM4T1YxYmlUSkJjX1JYTXJqUFlJUVhaQ3dsX19fZTJraHJPaGdpRnppSUp0NlNpLVZ3cWJQQUk9)
                REACT_APP_STORAGE_BUCKET: Encrypted(Z0FBQUFBQmZ3NWpLeHZHRHhCX0JOSEw3blQ1amJnWWc3eUYxQ1pkLXVQTWQtQ1YyX2JTUDF5Y2N3TVk5WDdZUjVIbXZKWUk5V0llN3VFVlJ1bHhBZHZOUEdTYmV5aG02RHBiS0FPd2c0ZjF2c1h2dl9yQkVXWmM9)
                REACT_APP_MESSAGING_SENDER_ID: Encrypted(Z0FBQUFBQmZ3NWpWNFk2RHdXclJIa1kxc0pOU3BVWmI3YlFVTFdQaHZ3TUs1cUJDUTRNb1dYaXRYSTYyeVp0WmVSLXBDYTRudDV3cW00cUkwbDF3Zmx0OGhzdklVcVg3VEE9PQ==)
                REACT_APP_APP_ID: Encrypted(Z0FBQUFBQmZ3NWplckJwUThfN3QtQlZBMXYwbmRKelJuYnRIZVc2OUEwRTdZMlY3N0o2QmFnRUY3U19pUDd6Z00wMDBTcUowUzNNQXlZSDltNUI1SnY2cm5LeGhFVjlYUTlqVDNIbk9mX09LWllNQklzQWRPOHVBOWhMWHk5eWxKVUNzVnB5UkJMTjA=)
                REACT_APP_MEASUREMENT_ID: Encrypted(Z0FBQUFBQmZ3NWpzNU0wTnUtS0lSTE11OTlxZ05lSjl2NkwtUUVqVFVIdllpMEFYWnUxdUtDSzBOcWI5VXRPc0p2RGpwWVhJZXhJSGV2NlZDQk1jWXF5YW9obWVhSFVfMEE9PQ==)
                REACT_APP_GOOGLE_MAPS_KEY: Encrypted(Z0FBQUFBQmZ3NWozU0hpVWF1cjJXcUJkY0Jsbm1Kb3RSd1dOTlptZ2FIcF9NUlEwTmZYQm9xYWhOdUo1Z0FzZjBWRHE3Z3dxWlFxOHJlQ1lteURqQmd0VmZNNm1nN0UtUFBvUTlOWDVESkZkR3AyRm9EMFpPbUVUb1IxMmRkajd4TnRTcF8xZ0pUNzg=)
                REACT_APP_FIREBASE_TOKEN: Encrypted(Z0FBQUFBQmZ3NWtHODVsT2dDQ1pMTTlVYnk5MGF0LTZJRmZrVEJmLUhlcWMwbEtybXVKeXJxX2QyMVVYR0pIcEVMMlAwdGpBd0FzeE0tS3R2UVcwNjNCSmJkZFZ1TzZVbEhjWVNJWjFfbjRHajVTSlJ6REdRSkNGUV9vQURNVG9Pc2FPNFZ2akRtTzdvSnU4djNFN2VXa2Jqd05ab2lYWUd4c3FfTk9udUtBNlhrc3lTdzFZWmVPcnFlY3pHSk01b1lXd1BRS2hEZkh1VFF1ek9tenFxY1hDNFd2VFdVVW51QT09)
                REACT_APP_FUNCTIONS_PATH: Encrypted(Z0FBQUFBQmZ3NWtZYnc2NjRyOHVTd192bHczaDBpRm1iLWVWZ2VXNk53VUhUdFRISEVnRC0za2RLRU1ETmpMdkI5V1hkQnN5Szk2ZGd0T0hyTFRlbm9Wd2k1cXhrMGRiTE1KRlRQS09vT0ZVYmlybjZKU1pqQUpUVXRyMldheUgtNFhzNnE0ZjB6Skd5SUtfVTdHZGV2UlZCQ0Z1QU1Icl9RPT0=)
                REACT_APP_STRIPE_PUBLISHABLE_KEY: Encrypted(Z0FBQUFBQmZ3NWtwS3BZZWNjSm5RUklPOHI2cDl4ai1HbkNJbEpJM3pqam1jUF9sdVVjNENLQmk3djIzSk5mOF84a00tczNXbUItYXZvV1FtREp0YmZkTkJPUHFtYnBObTVyM2JlTmVLTUFMOWVDZ2lGRTZaOVVHbFI1OFMyU3VZZUh6OGpOTHR4Y1h1cEluSzNxZlRPajhuQ01xX0RiTnBvN29xMDctTFNLSEJLeloxenlqa0VzRVNUQUVEbkotdEMwejJaQ0J4RTVIX3hGSlpJeG1PSzRya3g2ZHB3MEhRUT09)
                REACT_APP_STRIPE_SECRET_KEY: Encrypted(Z0FBQUFBQmZ3NWs0LV9CbVYxMjJUeFJidzdrMFRnWjhYSjJLZWU3WjM4MDVrcjc0bVpLRUFnNldzMHRtVm1iZFFDVE1hNXNGYUM2Qm96SFduOTZ2bjR0Rml3ZDlKTzBsS1djTHg1OEkyUWdqVjYzaGc4MjhHQlhPa1Nla1Q5NngtdHk0RDhvZFJ4TVQzU0FobmFJUkZGdnVrMmcteFBBc2hYckM3M2ZEZjRrWllyYlh1MXdNT0Jib1c2SVpUY2duMEFxbl9QOU5jMzN6d0xob3FFS2NDQ0JUYVRtTDQySkNQZz09)
                FIREBASE_TOKEN: Encrypted(Z0FBQUFBQmZ3NWtHODVsT2dDQ1pMTTlVYnk5MGF0LTZJRmZrVEJmLUhlcWMwbEtybXVKeXJxX2QyMVVYR0pIcEVMMlAwdGpBd0FzeE0tS3R2UVcwNjNCSmJkZFZ1TzZVbEhjWVNJWjFfbjRHajVTSlJ6REdRSkNGUV9vQURNVG9Pc2FPNFZ2akRtTzdvSnU4djNFN2VXa2Jqd05ab2lYWUd4c3FfTk9udUtBNlhrc3lTdzFZWmVPcnFlY3pHSk01b1lXd1BRS2hEZkh1VFF1ek9tenFxY1hDNFd2VFdVVW51QT09)
                CI: "false"
            node: latest
        triggering:
            events:
                - push
            branch_patterns:
                - pattern: master
                  include: true
                  source: true
        scripts:
            - name: Yarn install
              script: yarn install
            - name: Yarn build
              script: |
                CI=''
                yarn run build
            - name: Publish to firebase hosting
              script: |
                firebase use production --token $FIREBASE_TOKEN
                firebase deploy --token $FIREBASE_TOKEN
    react-native:
        name: Development Release
        instance_type: mac_mini
        max_build_duration: 120
        environment:
            vars:
                XCODE_WORKSPACE: "Constructo2"
                XCODE_SCHEME: "Constructo2"
                REACT_APP_API_KEY: Encrypted(Z0FBQUFBQmZ3NWxwVDltR1B3RnlOeFJvdHBIelVTaTU2QzFiRjNzX0puWWV2cFUzb3Ixb0Vrb0pHZHRlYlBfaVAwLW9lMkZfLVN1VC1tZTFpT1NDZ1BKenFnamtFM2Q0UEhWSEhnNTRQQjRxS3dzN3RSc28yOGhwUXlXRFdjTTVNZnZrRG5pTzN5WlI=)
                REACT_APP_AUTH_DOMAIN: Encrypted(Z0FBQUFBQmZ3NWx6RGlfdlJibUwtN2U2dGc5TEtaUWlYM20yMHY0TkxwendhNUNSSlJpV2wwTVN1VW9jV05sbk1MYkVjSEFYUy1Dd2NlXzM1NXNiNWo4d202ZWd0YUFHejZZdWcxbWt4LUNReGpfUUZZVF9HdDg4MnJhbTI3aENsb3VhTVR1REJGRzM=)
                REACT_APP_DATABASE_URL: Encrypted(Z0FBQUFBQmZ3NWw3YjRXQU04Q0pMaEgwWF8xeTFmTUxSYlJJYno1cTJmR216YXQ5OEc3ZXBuV0lfRjBiR2VISmpQMXF2azFoR3R2akhRbHNkS2pQSmdlX2NpRDZVOFBVQXpabXRJSTd1ZEhuYnBiVXJyc2hhSkRhMlJLZXl2MHRiSHRyUHJBaWpwRm4=)
                REACT_APP_PROJECT_ID: Encrypted(Z0FBQUFBQmZ3NW1FT0xaQXAtU3BnTzB3d1Z3d0hUQjhGQndWSFNldFgya2pWSllGMVdBazZlQVdIUzlnZjdRUG85cHhWNXhILUota2hRczMxdl9vNWlPY1lGOTNsMkRGa2UtZDd1TXdXTTJpaDFpSTBRVnA5WUE9)
                REACT_APP_STORAGE_BUCKET: Encrypted(Z0FBQUFBQmZ3NW1Od0RzbS1BMmFISjU0T3lmaFpDRElUOEFPSDg0RmtGTWl1UVBLSWc0bnpPQmZ3R0JzY19ibk12LUZuOVVmODItQU9LTkpIRmU1ZHdReFp3SmozS29FeXFOVkF4MS1SVHRxTHNIUk5mX0VNRHZIWFRKY1lmZnZxdS1XdjB1bGE0Ym4=)
                REACT_APP_MESSAGING_SENDER_ID: Encrypted(Z0FBQUFBQmZ3NW1ZYTdnUkVGVEl6VEhwNlVFRURqdFpuSkttSEloWUJlbDA5ZHltd1haYm84Si1pSXVSSWN6NTZHbTIyX01zNWJyNm45YmVPeUNUdzh6Q2RFLWkxUWFEZEE9PQ==)
                REACT_APP_APP_ID: Encrypted(Z0FBQUFBQmZ3NW1qLWNqSTRieG5lWGdCM3N2WFBMdTFpZnAtQWJLUEpuSjFLZG1kanpFZ204enMzUFh6VHpRYkRCQnY5clZUWHN5QzFLX1FwUGtXVHhlY2VIak13c1p1VjhqZ2wwdTZQVGp1TDk0TVRscktzYWVrV0o5dTJhVURDc0pjejFXdURHUk0=)
                REACT_APP_MEASUREMENT_ID: Encrypted(Z0FBQUFBQmZ3NW1zRWhfMmFlV25kSHBVWGMzZjNHZ2pXek9PUTh3bF9BSGhqbFlhOF95R0NjaDFvWTB4ZWpreUNpRG1NZHFXYmtGLTVlbFduR2Jid2FQOTZubUF5b1A2T0E9PQ==)
                REACT_APP_GOOGLE_MAPS_KEY: Encrypted(Z0FBQUFBQmZ3NW0zUDdvSU96by1BTmtBTGJCZE52S05qMzl3bzBKREI2Z0xqSlRoUkxDeFdhLXgtb0J4TmFodmI3cHpGdlZMOUcwQV95cFZXUGhXYUpNRGhPTFlZdVlWOUxzUEszUmNVLUJPQlZKbk5TR3NDcHhKZThyUGR1NkJFOW9aN2hyM1pUSzI=)
                REACT_APP_FIREBASE_TOKEN: Encrypted(Z0FBQUFBQmZ3NW5GQ1lNY0RvUEJJNlJ3aFRyVldqREFUQUIzck0xMHg1R0djdjdKNmd3YlpmbVF1OFlBeFZzaWtGWFF4U2tpem5FU3dDS2c0YzFlWW1WNzRwelFULUNxaE9wVWhHYm1CaG5yVlg3UnJ0SjdLOTVkVW9jRVl6RWo4UzNqaWlEN2haNjk0RllOQVhERjd4cGFqUjQ3WHFKellPclJLSVBTSG1TNUY5RGFIcnBFR01tZ3p2cGxWNlNac0YxaTR2SXVFcnluTXN4Mk4zQlBFQVR5T0tjd3RzLTZHdz09)
                REACT_APP_FUNCTIONS_PATH: Encrypted(Z0FBQUFBQmZ3NW5ubnFKM291cW4tWG50cko0cnpidlMtTENNOTFRMWJJVENxYXRQYzRVejVpRm5ZNnpjdm55ZTNDQkdwNVZMZ0pGSWtfcHFua1dwVmdPczZxWDcybnFaeVhnZFJJdmI4TThENjhhakNkU0RsN0ZGUXNESjg1cldnR3JCTTE3cVh1bkFvb01YV1hWM190RHZaT2MtTXoxbUhnPT0=)
                REACT_APP_STRIPE_PUBLISHABLE_KEY: Encrypted(Z0FBQUFBQmZ3NWtwS3BZZWNjSm5RUklPOHI2cDl4ai1HbkNJbEpJM3pqam1jUF9sdVVjNENLQmk3djIzSk5mOF84a00tczNXbUItYXZvV1FtREp0YmZkTkJPUHFtYnBObTVyM2JlTmVLTUFMOWVDZ2lGRTZaOVVHbFI1OFMyU3VZZUh6OGpOTHR4Y1h1cEluSzNxZlRPajhuQ01xX0RiTnBvN29xMDctTFNLSEJLeloxenlqa0VzRVNUQUVEbkotdEMwejJaQ0J4RTVIX3hGSlpJeG1PSzRya3g2ZHB3MEhRUT09)
                REACT_APP_STRIPE_SECRET_KEY: Encrypted(Z0FBQUFBQmZ3NWs0LV9CbVYxMjJUeFJidzdrMFRnWjhYSjJLZWU3WjM4MDVrcjc0bVpLRUFnNldzMHRtVm1iZFFDVE1hNXNGYUM2Qm96SFduOTZ2bjR0Rml3ZDlKTzBsS1djTHg1OEkyUWdqVjYzaGc4MjhHQlhPa1Nla1Q5NngtdHk0RDhvZFJ4TVQzU0FobmFJUkZGdnVrMmcteFBBc2hYckM3M2ZEZjRrWllyYlh1MXdNT0Jib1c2SVpUY2duMEFxbl9QOU5jMzN6d0xob3FFS2NDQ0JUYVRtTDQySkNQZz09)
                FIREBASE_TOKEN: Encrypted(Z0FBQUFBQmZ3NW5GQ1lNY0RvUEJJNlJ3aFRyVldqREFUQUIzck0xMHg1R0djdjdKNmd3YlpmbVF1OFlBeFZzaWtGWFF4U2tpem5FU3dDS2c0YzFlWW1WNzRwelFULUNxaE9wVWhHYm1CaG5yVlg3UnJ0SjdLOTVkVW9jRVl6RWo4UzNqaWlEN2haNjk0RllOQVhERjd4cGFqUjQ3WHFKellPclJLSVBTSG1TNUY5RGFIcnBFR01tZ3p2cGxWNlNac0YxaTR2SXVFcnluTXN4Mk4zQlBFQVR5T0tjd3RzLTZHdz09)
                CI: "false"
            node: latest
        triggering:
            events:
                - push
            branch_patterns:
                - pattern: develop
                  include: true
                  source: true
        scripts:
            - name: Yarn install
              script: yarn install
            - name: Yarn build
              script: yarn run build
            - name: Publish to firebase hosting
              script: |
                firebase use dev --token $FIREBASE_TOKEN
                firebase deploy --token $FIREBASE_TOKEN
                
