export const recordData = {
  ref: '',
  ID: '',
  userID: '',
  userName: '',
  projectID: '',
  createdAt: '',
  updatedAt: '',
  deletedAt: null,
  timestamp: '',
  deleted: false,
  content: '',
  category: '',
  positionIn: '',
  positionOut: '',
  signedAt: null,
  signedUrl: null,
  signed: false,
  tags: [],
  requestsForConfirmation: [],
  confirmedRequestsForConfirmation: [],
  requestsForRead: [],
  confirmedRequestsForRead: [],
  rejections: [],
  chatUsersRead: [],
  legacy: null,
  legacyID: null,
  legacyContent: null,
}

export const filesData = {
  ref: '',
  ID: '',
  userID: '',
  userName: '',
  projectID: '',
  createdAt: '',
  updatedAt: '',
  timestamp: '',
  deleted: false,
  name: null,
  module: 'diary',
  ext: '',
  mime: '',
  type: '',
  position: '',
  parentRelatedRef: '',
  activeVersion: true,
  isFolder: false,
  isVersion: false,
  version: 1,
  isCompressed: true,
  compression: 'zlib',
  storageUrl: '',
  folderRef: null,
  fileDescription: null,
  sizeInGB: '',
  online: true,
}

export const Signature = {
  ref: '',
  ID: '',
  userID: '',
  userName: '',
  projectID: '',
  createdAt: '',
  updatedAt: '',
  deletedAt: null,
  timestamp: '',
  deleted: false,
  tags: [],
  platform: 'WEB_1.0.0 + web browser',
  parentRef: '',
  parentID: '',
  signature: '',
  position: '',
}

export const keyEntity = {
  ref: '',
  ID: '',
  userID: '',
  userName: '',
  projectID: '',
  createdAt: '',
  updatedAt: '',
  deletedAt: null,
  timestamp: '',
  deleted: false,
  tags: [],
  platform: 'WEB_1.0.0 +web browser',
  signatureRef: '',
  signatureID: '',
  signature: '',
  key: '',
  keyType: '',
  position: '',
}
