const actions = {
  SET_STATE: 'project/SET_STATE',
  CREATE: 'project/CREATE',
  GET_ALL_PROJECTS: 'projects/GET',
  SET_PROJECT_ID: 'project/SET_PROJECT_ID',
  GET_USER_PROJECT: 'project/GET_USER_PROJECT',
  GET_PROJECT_BY_ID: 'project/GET_PROJECT_BY_ID',
  DELETE_PROJECT: 'project/DELETE_PROJECT_BY_ID',
  ADD_USER_TO_PROJECT: 'project/ADD_USER_TO_PROJECT',
  UPLOAD_NEW_ROLE: 'project/UPLOAD_NEW_ROLE',
  UPDATE_OLD_ROLE: 'project/UPDATE_OLD_ROLE',
  UPDATE_OLD_ROLE_USERS: 'project/UPDATE_OLD_ROLE_USERS',
  DELETE_ROLE: 'project/DELETE_ROLE',
  REMOVE_USERS_FROM_PROJECT: 'project/REMOVE_USERS_FROM_PROJECT',
  REMOVE_PENDING_REQUEST: 'project/REMOVE_PENDING_REQUEST',
  RECOVER_PROJECT: 'project/RECOVER_PROJECT',
  CURRENT_PROJECT_ROLE: 'project/CURRENT_ROLE',
}

export default actions
