export const UserModel = {
  userID: '',
  ID: '',
  createdAt: '',
  deleted: false,
  name: '',
  surname: '',
  title: '',
  phone: '',
  email: '',
  avatar: '',
  projects: [],
}

export const ProjectModel = {
  ref: '',
  ID: '',
  avatar: null,
  userID: '',
  userName: '',
  projectID: '',
  createdAt: '',
  updatedAt: '',
  deletedAt: '',
  timestamp: '',
  deleted: false,
  name: '',
  street: '',
  city: '',
  zip: '',
  state: '',
  location: '',
  estimatedStart: '',
  estimatedFinish: '',
  identifier: null,
  users: [],
  pendingRegistrations: [],
  tags: null,
  taskCategories: null,
  diaryCategories: null,
  spaceLimit: 1,
  spaceUsed: 0,
  userLimit: 0,
  userUsed: 0,
  projectDescription: null,
  attendanceKey: null,
  backupPeriod: null,
  active: true,
  subscriptionPlanValidUntil: null,
  legacy: null,
  legacyID: null,
  legacyContent: null,
  filesLimit: 25,
}

export const RoleModels = {
  ProjectCreatorRole: {
    createdAt: null,
    updatedAt: null,
    deleted: false,
    roleName: 'PROJECT_CREATOR',
    projectRule: 'WRITE',
    filesRule: 'WRITE',
    filesDeleteRule: true,
    rolesRule: 'WRITE',
    diaryRule: 'WRITE',
    versionsRule: 'WRITE',
    signingRule: 'WRITE',
    admin: true,
    superAdmin: false,
    users: [],
  },
  OrdinaryRole: {
    createdAt: null,
    updatedAt: null,
    deleted: false,
    roleName: 'ORDINARY',
    projectRule: 'READ',
    rolesRule: 'WRITE',
    diaryRule: 'WRITE',
    filesRule: 'WRITE',
    filesDeleteRule: false,
    versionsRule: 'WRITE',
    signingRule: 'WRITE',
    admin: false,
    superAdmin: false,
    users: [],
  },
  GuestRole: {
    createdAt: null,
    updatedAt: null,
    deleted: false,
    roleName: 'GUEST',
    projectRule: 'READ',
    rolesRule: 'READ',
    diaryRule: 'READ',
    filesRule: 'READ',
    filesDeleteRule: false,
    versionsRule: 'READ',
    signingRule: 'READ',
    admin: false,
    superAdmin: false,
    users: [],
  },
  SuperSystemAdminRole: {
    createdAt: null,
    updatedAt: null,
    deleted: false,
    roleName: 'SYSTEM_ADMIN',
    projectRule: 'READ',
    rolesRule: 'READ',
    filesDeleteRule: true,
    diaryRule: 'READ',
    filesRule: 'READ',
    versionsRule: 'READ',
    signingRule: 'READ',
    userID: '',
    admin: false,
    superAdmin: false,
    users: [],
  },
}

export const FolderModel = {
  ref: '',
  userID: '',
  userName: '',
  projectID: '',
  createdAt: '',
  updatedAt: '',
  timestamp: '',
  deleted: false,
  name: '',
  module: 'diary',
  ext: null,
  mime: null,
  type: null,
  position: '',
  parentRelatedRef: null,
  parentVersionRef: null,
  activeVersion: true,
  isFolder: false,
  isVersion: false,
  version: 1,
  isCompressed: true,
  compression: 'zlib',
  sizeInGb: null,
  online: true,
  fileDecription: null,
}

export const RecordModel = {
  ref: '',
  ID: '',
  userID: '',
  userName: '',
  projectID: '',
  createdAt: '',
  updatedAt: '',
  deletedAt: null,
  timestamp: '',
  deleted: false,
  content: '',
  category: '',
  positionIn: '',
  positionOut: '',
  signedAt: null,
  signedUrl: null,
  signed: false,
  tags: [],
  requestsForConfirmation: [],
  confirmedRequestsForConfirmation: [],
  requestsForRead: [],
  confirmedRequestsForRead: [],
  rejections: [],
  chatUsersRead: [],
  legacy: null,
  legacyID: null,
  legacyContent: null,
}

export const FileModel = {
  ref: '',
  userID: '',
  userName: '',
  projectID: '',
  createdAt: '',
  updatedAt: '',
  timestamp: '',
  deleted: false,
  name: null,
  module: 'diary',
  ext: '',
  mime: 'Composed MIME (in case it is possible tocompose it)',
  type: '',
  position: '',
  parentRelatedRef: '',
  parentVersionRef: '',
  activeVersion: true,
  isFolder: false,
  isVersion: false,
  version: 1,
  isCompressed: true,
  compression: 'zlib',
  storageUrl: '',
  fileDescription: null,
  sizeInGb: '',
  online: true,
}

export const KeyModel = {
  ref: '',
  ID: '',
  userID: '',
  userName: '',
  projectID: '',
  createdAt: '',
  updatedAt: '',
  deletedAt: null,
  timestamp: '',
  deleted: false,
  tags: [],
  platform: 'WEB_1.0.0 +web browser',
  signatureRef: '',
  signatureID: '',
  signature: '',
  key: '',
  keyType: '',
  position: '',
  method: 'RSA-PKCS8PRV',
  base64: false,
}

export const LogModel = {
  ref: 'ref',
  ID: '',
  userID: '',
  userName: '',
  projectID: '',
  createdAt: '',
  updatedAt: '',
  deletedAt: null,
  timestamp: '',
  deleted: false,
  deviceId: null,
  entityRef: '',
  entityRefID: '',
  platform: '',
  logDescription: 'file cloud content delete',
  note: null,
  location: '',
  ancestor: null,
}

export const DeletionModel = {
  ref: '',
  userID: '',
  module: 'diary or files',
  projectID: '',
  deletionRef: '',
  deletionID: '',
  deletionAt: '',
}

export const SignatureModel = {
  ref: '',
  ID: '',
  userID: '',
  userName: '',
  projectID: '',
  createdAt: '',
  updatedAt: '',
  deletedAt: null,
  timestamp: '',
  deleted: false,
  tags: [],
  platform: 'WEB_1.0.0 + web browser',
  parentRef: '',
  parentID: '',
  signature: '',
  position: '',
  method: 'RSA-PKCS8PRV',
  base64: false,
  verificationKey: '',
  verificationMethod: 'sms',
}

export const WeatherModel = {
  ref: '',
  ID: '',
  projectID: '',
  createdAt: '',
  updatedAt: '',
  deletedAt: null,
  timestamp: '',
  deleted: false,
  mainTemperature: Number,
  windSpeed: Number,
  rain: Number,
  pressure: Number,
  humidity: Number,
  icon: String,
}
export const logs = {
  ref: 'ref',
  ID: '',
  userID: '',
  userName: '',
  projectID: '',
  createdAt: '',
  updatedAt: '',
  deletedAt: null,
  timestamp: '',
  deleted: false,
  location: '',
  deviceId: null,
  entityRef: '',
  entityRefID: '',
  platform: '',
  logDescription: 'file cloud content delete',
  note: null,
  ancestor: null,
}
